const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),now=()=>Date.now(),rid=p=>p+Math.random().toString(36).slice(2,8),DAY=864e5,KEY='trueai_hq_demo_v1';
const fd=n=>n?new Date(n).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—',ft=n=>n?new Date(n).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Never';
const ST=['Not Started','In Progress','Review','Completed'],KD=['Task','Bug','Feature','UI Task','UI Bug'],RN={owner:'Owner',co:'Co-Administrator',ui:'UI Designer'};
const PM={owner:'cc reviews tasks design analytics activity ann annw notifs security settings staff progress dreview',co:'cc reviews tasks analytics activity ann annw notifs security settings progress',ui:'cc design tasks analytics ann notifs security settings'};
const NAV=[['cc','Command Center'],['reviews','Reviews'],['tasks','Tasks'],['design','Design Studio'],['analytics','Analytics'],['activity','Activity'],['ann','Announcements'],['notifs','Notifications'],['security','Security'],['settings','Settings'],['staff','Staff Management']];
const O1='TRUEAI-HQ-0001',O2='TRUEAI-HQ-0002',O3='TRUEAI-HQ-0003',A={},F={},C={};
const TK=(t,to,pri,st,due,kind,desc)=>({id:rid('t'),title:t,to,pri,st,due:now()+due*DAY,at:now()-5*DAY,kind,desc,cm:[],h:[[now()-5*DAY,'Task created']]});
const RV=(r,x,src,d,cat,st,to,rs)=>({id:rid('r'),rating:r,text:x,src,at:now()-d*DAY,cat,st,to,resp:rs,notes:[]});
function seed(){return{staff:[[O1,'Shaashwat Misra','shaashwat.demo@gmail.com','owner'],[O2,'Pranav Maurya','pranav.demo@gmail.com','co'],[O3,'Shubh Mishra','shubh.demo@gmail.com','ui']].map(([id,name,email,role])=>({id,name,email,role,status:'invited',inv:'Pending',last:0})),auth:{},sess:[],fails:{},pf:{},
tasks:[TK('Design Briz AI onboarding screens',O3,'High','In Progress',5,'UI Task','First-run flow for the Android app.'),TK('Fix response timeouts on long prompts',O2,'High','Not Started',2,'Bug','Core model times out on long inputs.'),TK('WhatsApp webhook integration spec',O2,'Medium','Review',9,'Feature','Define message flow and retries.'),TK('Session handling security review',O1,'Medium','Completed',-1,'Task','Audit token lifetime and revocation.'),TK('Fix button contrast in dark theme',O3,'Low','Not Started',7,'UI Bug','Several secondary buttons fail contrast.')],
reviews:[RV(5,'Fast and surprisingly accurate answers.','Play Store',2,'Praise','Resolved',O2,'Responded'),RV(2,'App freezes when I paste long text.','Play Store',5,'Bug','New','','Not Responded'),RV(4,'Love the clean look, wish it had widgets.','Website',12,'Feature request','In Progress',O3,'Not Responded'),RV(3,'Responses are good but slow sometimes.','Email',20,'Performance','New','','Not Responded'),RV(5,'Best assistant I have tried on WhatsApp.','WhatsApp',33,'Praise','Resolved',O2,'Responded'),RV(1,'Login failed twice on my phone.','Play Store',47,'Bug','In Progress',O2,'Not Responded'),RV(4,'Text is small in settings.','Website',62,'UI/UX','New','','Not Responded'),RV(5,'Great tool for daily notes.','Play Store',80,'Praise','Resolved',O3,'Responded')],
designs:[{id:'d1',name:'Briz AI chat home',by:O3,rev:O1,due:now()+4*DAY,st:'Awaiting Approval',v:2,fb:[]},{id:'d2',name:'Onboarding flow',by:O3,rev:O1,due:now()+8*DAY,st:'Draft',v:1,fb:[]},{id:'d3',name:'Settings screens',by:O3,rev:O1,due:now()+3*DAY,st:'In Revision',v:3,fb:[{u:O1,at:now()-DAY,x:'Increase text size and spacing.'}]}],
ann:[{id:'a1',title:'Welcome to TRUEAI Headquarters',body:'This is the internal home for the Briz AI project. Keep tasks and reviews up to date.',pri:'Normal',pin:1,at:now()-2*DAY,exp:0,by:O1,rd:[]}],notifs:[],act:[],
prog:[['Core AI',62],['Android App',45],['WhatsApp Integration',28],['UI/UX',54],['Security',40],['Website',70],['Testing',22]].map(([n,p],i)=>({n,p,u:now()-(i+1)*DAY}))}}
let S;try{S=JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){S=seed()}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}};
const enc=new TextEncoder(),rnd=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hp(pw,salt){const k=await crypto.subtle.importKey('raw',enc.encode(pw),'PBKDF2',false,['deriveBits']),b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},k,256);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const gs=()=>{try{return sessionStorage.getItem('tq_sid')||localStorage.getItem('tq_sid')}catch(e){}},ss=(v,rem)=>{try{sessionStorage.removeItem('tq_sid');localStorage.removeItem('tq_sid');v&&(rem?localStorage:sessionStorage).setItem('tq_sid',v)}catch(e){}};
let me=null,V={r:'cc',q:'',f:'',pf:'',so:'',tab:'Account',load:0},AU=null,RS=null,MH=null,PI=[],PX=0,LR='',busy=0;
const can=p=>!!me&&PM[me.role].split(' ').includes(p),perm=r=>r==='profile'?'settings':r,pf=()=>{const p=S.pf[me.id]||(S.pf[me.id]={});for(const k in PD)if(p[k]===undefined)p[k]=typeof PD[k]==='object'?JSON.parse(JSON.stringify(PD[k])):PD[k];return p};const PD={theme:'dark',accent:'blue',dens:'comfortable',anim:'full',glass:1,bgfx:1,land:'cc',big:0,hc:0,snd:0,lvl:'all',np:{},w:{prog:1,my:1,act:1,ann:1,qa:1},first:'prog',rs:[],tv:'list'};
const nm=id=>(S.staff.find(s=>s.id===id)||{}).name||'Unassigned',vis=t=>!t.arch&&(me.role!=='ui'||t.kind.includes('UI')||t.to===me.id),ini=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2),invS=s=>s.inv==='Pending'&&s.exp&&s.exp<now()?'Expired':s.inv;
const log=(a,it,u=me&&me.id,sec)=>{S.act.unshift({id:rid('l'),u,a,it,at:now(),sec:!!sec});S.act.length=Math.min(S.act.length,300)};
const notify=(to,type,text,r,key)=>{if(key&&S.notifs.some(n=>n.key===key))return;S.notifs.unshift({id:rid('n'),to,type,text,r,at:now(),rd:[],cl:[],key});me&&pf().snd&&(to==='all'||to.includes(me.id))&&beep()};
const NT={'Task assignment':'Task assignments','Task update':'Task updates','Task deadline':'Task deadlines','New review':'Reviews','Design feedback':'Design feedback','Announcement':'Announcements','Progress':'Announcements','Security':'Security alerts','Account':'Account events','Invitation':'Account events'},NCAT={'Task assignment':'Tasks','Task update':'Tasks','Task deadline':'Tasks','New review':'Reviews','Design feedback':'Designs','Announcement':'Announcements','Progress':'Announcements','Security':'Security','Account':'Account','Invitation':'Account'};
const mine=()=>{const p=pf();return p.lvl==='none'?[]:S.notifs.filter(n=>(n.to==='all'||n.to.includes(me.id))&&!n.cl.includes(me.id)&&p.np[NT[n.type]]!==0&&(p.lvl!=='imp'||['Security','Account','Task deadline','Task assignment','Invitation'].includes(n.type)))};
function toast(m,t){t=t||(/permission|access to|invalid|incorrect|protected|cannot|already in use|not active/i.test(m)?'e':'s');if([...document.querySelectorAll('.toast')].some(x=>x.dataset.m===m))return;const e=document.createElement('div');e.className='toast '+t;e.dataset.m=m;e.setAttribute('role','status');e.innerHTML=`<i>${{s:'✓',i:'ℹ',w:'⚠',e:'✕'}[t]}</i>${esc(m)}`;const x=()=>{e.classList.add('x');setTimeout(()=>e.remove(),300)};e.onclick=x;$('#toasts').append(e);setTimeout(x,3200)}
const guard=p=>can(p)||(toast('You do not have permission for that.'),false),fin=m=>{save();render();toast(m)};
function modal(t,body,ok,label='Save',dr){$('#modal').innerHTML=`<form class="mb${dr?' dr':''}" data-f="modal" role="dialog" aria-modal="true" aria-label="${esc(t)}"><div class="row"><h2>${esc(t)}</h2><button type="button" class="btn sm" data-a="mx" aria-label="Close">✕</button></div>${body}${ok?`<div class="row end"><button type="button" class="btn" data-a="mx">Cancel</button><button class="btn pri">${label}</button></div>`:''}</form>`;MH=ok;LF=document.activeElement;$('#modal').className='on'+(dr?' dr':'');const i=$('#modal input,#modal select,#modal textarea');(i||$('#modal .mb button')).focus()}
let LF;const mx=()=>{$('#modal').className='';MH=null;LF&&LF.focus&&LF.focus()},ask=(m,fn)=>modal('Please confirm',`<p>${m}</p>`,()=>{mx();fn()},'Confirm');
const bdg=(t,c='')=>`<span class="bd ${c}">${esc(t)}</span>`,pc=p=>({High:'e',Medium:'w'}[p]||''),
opts=(a,v)=>a.map(x=>{const[k,l]=Array.isArray(x)?x:[x,x];return`<option value="${esc(k)}"${k==v?' selected':''}>${esc(l)}</option>`}).join(''),
so=v=>opts([['','Unassigned'],...S.staff.filter(s=>s.status!=='inactive').map(s=>[s.id,s.name])],v),
tbl=(h,r,e)=>r.length?`<div class="tw"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.join('')}</tbody></table></div>`:`<p class="empty">${e}</p>`,
srch=(ph,x='')=>`<div class="tb"><input id="q" data-i="q" placeholder="${ph}" aria-label="${ph}" value="${esc(V.q)}">${x}</div>`,
panel=(t,b,a='')=>`<section class="panel"><div class="row"><h2>${t}</h2><div>${a}</div></div>${b}</section>`,
bar=(l,v,m)=>`<div class="br"><span>${esc(l)}</span><div class="bar"><i style="width:${m?Math.round(v/m*100):0}%"></i></div><b>${v}</b></div>`;
const pwErr=(p,q)=>p.length<10?'Use at least 10 characters.':!/[a-z]/i.test(p)||!/\d/.test(p)?'Use both letters and numbers.':p!==q?'Passwords do not match.':'';
const strength=p=>{const s=(p.length>=10)+(p.length>=14)+(/[a-z]/.test(p)&&/[A-Z]/.test(p))+/\d/.test(p)+/[^\w\s]/.test(p);return p?'Strength: '+['Very weak','Weak','Fair','Good','Strong','Excellent'][s]:''};
const gen=O=>{O.code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);O.exp=now()+3e5;O.tries=0;O.rs=now()+3e4};
const chk=(O,c)=>{const bad='Invalid or expired code. Request a new one.';if(!O||!O.code||now()>O.exp||O.tries>=5)return bad;if(String(c).trim()!==O.code){O.tries++;return bad}return null};
const err=(m,ok)=>{const e=$('#err');if(e){e.textContent=m;e.className='err'+(ok?' okm':'')}};
const applyTheme=()=>{const p=me?pf():PD,h=document.documentElement.dataset,sys=matchMedia('(prefers-color-scheme: light)').matches;h.theme=p.theme==='system'?(sys?'light':'dark'):p.theme;h.dens=p.dens;h.accent=p.accent;h.anim=p.anim;h.glass=p.glass?1:0;h.bgfx=p.bgfx?1:0;h.big=p.big?1:0;h.hc=p.hc?1:0};
/* ---------- AUTH (DEMO MODE) ---------- */
function authView(m='login',msg='',ok=0){let pre='';try{pre=localStorage.getItem('tq_dev')||''}catch(e){}
const E=`<div id="err" class="err${ok?' okm':''}" role="alert">${esc(msg)}</div>`,back='<button class="lk" data-a="au" data-m="login">Back to sign in</button>',mail=(o,l)=>`<p class="demo">DEMO MODE — no email was sent. Simulated inbox:</p><div class="mail">${l}: <b>${o.code}</b><br><small>Expires in 5 minutes · single use</small></div>`;let b;
if(m==='act'){AU=AU||{step:1};const u=AU.u;b=AU.step===1?`<form data-f="a1">${E}<p class="m">Enter the Staff ID assigned to you by TRUEAI.</p><label for="x">Staff ID</label><input id="x" name="id" required autocomplete="off"><button class="btn pri wide">Continue</button></form><div class="links">${back}</div>`:AU.step===2?`<form data-f="a2">${E}<div class="kv"><span>Name</span><b>${esc(u.name)}</b><span>Role</span><b>${RN[u.role]}</b><span>Email</span><b>${esc(u.email)}</b></div><label>Create password</label><input type="password" name="pw" data-i="pw" autocomplete="new-password" required><small id="sm" class="m"></small><label>Confirm password</label><input type="password" name="pw2" autocomplete="new-password" required><p class="warn">⚠️ Remember this password. This password will be required for your future TrueAI Headquarters logins.</p><button class="btn pri wide">Send verification code</button></form><div class="links">${back}</div>`:`<form data-f="a3">${E}${mail(AU,'Your TRUEAI Headquarters verification code')}<label>6-digit code</label><input name="c" inputmode="numeric" maxlength="6" required autocomplete="one-time-code"><button class="btn pri wide">Verify and activate</button></form><div class="links"><button class="lk" data-a="rsd">Resend code</button>${back}</div>`}
else if(m==='reset'){RS=RS||{step:1};b=RS.step===1?`<form data-f="r1">${E}<p class="m">Enter your Staff ID or email.</p><label>Staff ID or email</label><input name="id" required><button class="btn pri wide">Send verification code</button></form><div class="links">${back}</div>`:`<form data-f="r2">${E}${RS.u?mail(RS,'Your TRUEAI Headquarters reset code'):''}<label>Verification code</label><input name="c" inputmode="numeric" maxlength="6" required><label>New password</label><input type="password" name="pw" data-i="pw" autocomplete="new-password" required><small id="sm" class="m"></small><label>Confirm new password</label><input type="password" name="pw2" autocomplete="new-password" required><button class="btn pri wide">Reset password</button></form><div class="links"><button class="lk" data-a="rsd">Resend code</button>${back}</div>`}
else b=`<form data-f="login">${E}<label for="li">Staff ID or Email</label><input id="li" name="id" autocomplete="username" required value="${esc(pre)}"><label for="lp">Password</label><input id="lp" name="pw" type="password" autocomplete="current-password" required><label class="ck"><input type="checkbox" name="rem"> Remember this device</label><button class="btn pri wide" id="lb">Sign In</button></form><div class="links"><button class="lk" data-a="au" data-m="reset">Forgot password?</button><button class="lk" data-a="au" data-m="act">First-time activation</button></div>`;
$('#app').innerHTML=`<div class="auth"><div class="acard"><div class="brand"><b>TRUEAI</b><span>HEADQUARTERS</span><small>Briz AI Operations &amp; Staff Command Center</small></div>${b}<p class="demo" style="margin-top:22px">DEMO MODE · frontend-only authentication, not production security</p></div></div>`;const i=$('.acard input');i&&i.focus()}
F.login=async f=>{if(busy)return;busy=1;const b=$('#lb');b.disabled=true;b.textContent='Signing in…';let m;try{m=await tryLogin(f)}catch(e){m='Something went wrong. Try again.'}busy=0;if(m){err(m);b.disabled=false;b.textContent='Sign In'}};
async function tryLogin(f){const k=f.id.trim().toLowerCase(),X=S.fails[k]||{n:0,until:0};if(X.until>now())return`Too many login attempts. Try again in ${Math.ceil((X.until-now())/1000)}s.`;
const u=S.staff.find(s=>s.id.toLowerCase()===k||s.email.toLowerCase()===k),a=u&&S.auth[u.id];if(u&&!a&&u.status!=='inactive')return'Verification required. Use first-time activation.';
const ok=!!a&&await hp(f.pw,a.salt)===a.hash;if(!ok){X.n++;if(X.n>=5){X.until=now()+3e4;X.n=0}S.fails[k]=X;u&&log('Failed login attempt','Invalid password',u.id,1);save();return'Invalid Staff ID or password'}
if(u.status==='inactive')return'Account inactive';delete S.fails[k];begin(u,!!f.rem);return''}
function begin(u,rem){const id=rid('s');S.sess.push({id,uid:u.id,dev:((navigator.userAgentData&&navigator.userAgentData.platform)||navigator.platform||'Browser')+' · '+((navigator.userAgent.match(/(Edg|Chrome|Firefox|Safari)/)||['Browser'])[0]),at:now()});ss(id,rem);try{rem?localStorage.setItem('tq_dev',u.id):localStorage.removeItem('tq_dev')}catch(e){}
u.last=now();me=u;log('Logged in','Session started',u.id,1);S.tasks.filter(t=>t.to===u.id&&t.st!=='Completed'&&t.due<now()+2*DAY).forEach(t=>notify([u.id],'Task deadline',`Due soon: ${t.title}`,'tasks','dl'+t.id));
save();applyTheme();const L=NAV.some(n=>n[0]===pf().land&&can(perm(n[0])))?pf().land:'cc';V={r:L,q:'',f:'',pf:'',so:'',tab:'Account',load:1};LR='';history.replaceState(null,'','#/'+L);arrive();render();setTimeout(()=>{V.load=0;render()},500)}
function arrive(){const a=document.createElement('div');a.id='arr';a.setAttribute('role','status');a.innerHTML='<div><b>TRUEAI</b><h1>We Welcome You To Headquarters Of TRUE AI</h1></div>';document.body.append(a);setTimeout(()=>a.classList.add('out'),3100);setTimeout(()=>a.remove(),3800)}
function logout(msg){if(me){S.sess=S.sess.filter(s=>s.id!==gs());log('Logged out','Session ended',me.id,1)}ss(null);me=null;save();document.documentElement.dataset.theme='dark';mx();A.pc();authView('login',msg||'')}
A.out=()=>logout();A.au=d=>{AU=null;RS=null;authView(d.m)};
F.a1=f=>{const u=S.staff.find(s=>s.id.toLowerCase()===f.id.trim().toLowerCase());if(!u||u.status!=='invited'||invS(u)!=='Pending'||S.auth[u.id])return err('This Staff ID cannot be activated. Contact the TRUEAI Owner.');AU={step:2,u};authView('act')};
F.a2=f=>{const e=pwErr(f.pw,f.pw2);if(e)return err(e);AU.pw=f.pw;gen(AU);AU.step=3;authView('act')};
F.a3=async f=>{const e=chk(AU,f.c);if(e)return err(e);const u=AU.u,salt=rnd();AU.code=null;S.auth[u.id]={salt,hash:await hp(AU.pw,salt)};u.status='active';u.inv='Activated';u.joined=now();log('Account activated',u.name,u.id,1);notify(S.staff.filter(s=>s.role==='owner').map(s=>s.id),'Account','Account activated: '+u.name,'staff');try{localStorage.setItem('tq_dev',u.id)}catch(x){}save();AU=null;authView('login','Account activated. Sign in with your new password.',1)};
A.rsd=()=>{const O=AU||RS;if(!O||!O.code)return;if(now()<O.rs)return err(`Please wait ${Math.ceil((O.rs-now())/1000)}s before requesting a new code.`);gen(O);authView(AU?'act':'reset')};
F.r1=f=>{const k=f.id.trim().toLowerCase(),u=S.staff.find(s=>(s.id.toLowerCase()===k||s.email.toLowerCase()===k)&&s.status==='active'&&S.auth[s.id]);RS={step:2,u:u||null};u&&gen(RS);authView('reset','If the details match a TRUEAI account, a verification code has been sent.',1)};
F.r2=async f=>{const e=chk(RS,f.c)||pwErr(f.pw,f.pw2);if(e)return err(e);const u=RS.u,salt=rnd();S.auth[u.id]={salt,hash:await hp(f.pw,salt)};S.sess=S.sess.filter(s=>s.uid!==u.id);log('Password reset',u.name,u.id,1);RS=null;save();authView('login','Password updated. All existing sessions were signed out.',1)};
/* ---------- SHELL ---------- */
const VW={cc,tasks,reviews,design,analytics,activity,ann,notifs,security,settings,staff,profile};
function render(){if(!me)return;if(!S.sess.some(s=>s.id===gs())||(S.staff.find(s=>s.id===me.id)||{}).status!=='active')return logout('Session expired. Please sign in again.');
if(!VW[V.r]||!can(perm(V.r)))V.r='cc';const un=mine().filter(n=>!n.rd.includes(me.id)).length,t=V.r==='profile'?'Profile':(NAV.find(n=>n[0]===V.r)||[0,''])[1];let b;
try{b=V.load?'<div class="cards" aria-busy="true"><div class="sk"></div><div class="sk"></div><div class="sk"></div><div class="sk"></div><div class="sk"></div><div class="sk"></div></div><p class="m" style="text-align:center">Loading Headquarters data…</p>':VW[V.r]()}catch(e){console.error(e);b='<div class="panel empty">Something went wrong. Try again.<br><br><button class="btn" data-a="rt">Retry</button></div>'}
const pg=V.r!==LR?'pg':'';LR=V.r;
$('#app').innerHTML=`<div id="shell"><aside id="side" aria-label="Primary"><div class="logo"><b>TRUEAI</b><small>HEADQUARTERS</small><span>Building Briz AI</span></div><nav>${NAV.filter(n=>can(perm(n[0]))).map(n=>`<button class="nv${V.r===n[0]?' on':''}" data-a="go" data-r="${n[0]}">${n[1]}${n[0]==='notifs'&&un?`<span class="cnt">${un}</span>`:''}</button>`).join('')}</nav><div class="me"><button class="nv${V.r==='profile'?' on':''}" data-a="go" data-r="profile">Profile</button><p class="who"><b>${esc(me.name)}</b><small>${RN[me.role]}</small></p><button class="btn" data-a="out">Logout</button></div></aside><div><header class="top"><button class="btn sm mbtn" data-a="menu" aria-label="Open menu">☰</button><div class="ttl">${t}</div><button class="srch" data-a="pal" aria-label="Search or run a command"><span>Search or run a command</span><kbd>Ctrl K</kbd></button><button class="btn sm" data-a="go" data-r="notifs">Notifications${un?` <span class="cnt">${un}</span>`:''}</button><button class="bd ok" data-a="go" data-r="security">Session secure · DEMO</button><div class="usr"><div class="av">${ini(me.name)}</div><div class="hide"><b>${esc(me.name)}</b><small>${RN[me.role]}</small></div></div></header><main id="mn" class="${pg}">${b}</main></div></div>`}
const go=r=>{if(!can(perm(r)))return toast('You do not have access to that section.');if(location.hash==='#/'+r)return render();location.hash='#/'+r};
addEventListener('hashchange',()=>{if(!me)return;V.r=location.hash.slice(2)||'cc';V.q=V.f=V.pf=V.so='';render();scrollTo(0,0)});
A.go=d=>go(d.r);A.rt=()=>render();A.menu=()=>$('#side').classList.toggle('open');A.mx=mx;A.tab=d=>{V.tab=d.t;render()};
/* ---------- COMMAND CENTER ---------- */
const RESP={'Core AI':O2,'Android App':O2,'WhatsApp Integration':O2,'UI/UX':O3,'Security':O1,'Website':O1,'Testing':O2},RT={owner:'Company direction, staff, security and Briz AI project controls.',co:'Briz AI project operations, reviews, tasks and announcements.',ui:'Briz AI UI/UX design, mockups, revisions and design feedback.'},pst=x=>x>=100?'Complete':x>=60?'On track':x>=30?'In progress':'Early';
const evs=l=>l.length?`<div class="tl">${l.map(a=>`<div class="ev"><div class="av">${ini(nm(a.u))}</div><div><b>${esc(nm(a.u))}</b> ${esc(a.a.toLowerCase())} <span class="m">· ${esc(a.it)}</span><br><small class="m">${ft(a.at)}</small>${a.sec?' '+bdg('Security','w'):''}</div></div>`).join('')}</div>`:'<p class="empty">No activity yet.</p>',
dl=t=>t.st==='Completed'?fd(t.due):t.due<now()?fd(t.due)+' '+bdg('Overdue','e'):t.due<now()+2*DAY?fd(t.due)+' '+bdg('Soon','w'):fd(t.due),
donut=(p,l)=>`<div class="dn"><svg viewBox="0 0 36 36" role="img" aria-label="${l} ${p}%"><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--b)" stroke-width="3"/><circle cx="18" cy="18" r="15.9" fill="none" stroke="var(--a)" stroke-width="3" stroke-linecap="round" stroke-dasharray="${p} ${100-p}" stroke-dashoffset="25" style="transition:stroke-dasharray .8s"/><text x="18" y="20.6" text-anchor="middle" font-size="7.5" fill="var(--t)">${p}%</text></svg><small class="m">${l}</small></div>`;
function beep(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);g.gain.value=.05;o.frequency.value=660;o.onended=()=>c.close();o.start();o.stop(c.currentTime+.12)}catch(e){}}
function SK(e){if(!me||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#modal').className||$('#pal').className)return;if(e.key==='/'){e.preventDefault();A.pal()}else if(e.key==='n'&&can('tasks')){e.preventDefault();A.tnew()}}
function revStats(){const rs=S.reviews,n=rs.length,avg=n?(rs.reduce((a,r)=>a+r.rating,0)/n).toFixed(1):'–',rr=n?Math.round(rs.filter(r=>r.resp==='Responded').length/n*100):0;return`<section class="panel"><div class="ov" style="grid-template-columns:1fr 1fr 2fr"><div><small class="m">Average rating</small><div class="big">${avg}</div></div><div><small class="m">Response rate</small><div class="big">${rr}%</div><small class="m">${rs.filter(r=>r.resp!=='Responded').length} pending</small></div><div>${[5,4,3,2,1].map(k=>bar(k+' ★',rs.filter(r=>r.rating===k).length,n)).join('')}</div></div></section>`}
function cc(){const p=pf(),w=p.w,ot=S.tasks.filter(t=>t.st!=='Completed'&&vis(t)),bugs=ot.filter(t=>t.kind.includes('Bug')).length,pr=S.reviews.filter(r=>r.st==='New').length,ac=S.staff.filter(s=>s.status==='active').length,un=mine().filter(n=>!n.rd.includes(me.id)).length,ov=Math.round(S.prog.reduce((a,x)=>a+x.p,0)/S.prog.length),my=ot.filter(t=>t.to===me.id),soon=my.filter(t=>t.due<now()+3*DAY).length,dq=S.designs.filter(d=>(d.rev===me.id&&['Submitted','Awaiting Approval'].includes(d.st))||(d.by===me.id&&['Draft','In Revision'].includes(d.st))).length,
qa=[['＋','New Task','tasks','tnew'],['★','Review Center','reviews','go:reviews'],['✎','New Announcement','annw','anew'],['◧','Design Studio','design','go:design'],['⊕','Invite Staff','staff','inv'],['⛨','Security','security','go:security'],['↑','Update Progress','progress','prog']].filter(q=>can(q[2])),
mini=(l,v)=>`<div class="pcard static"><small class="m">${l}</small><b class="n">${v}</b></div>`,
hero=`<div class="hero2"><div><small class="m">TRUEAI HEADQUARTERS</small><h1>Welcome back, ${esc(me.name.split(' ')[0])}.</h1><p class="m">Briz AI Operations &amp; Staff Command Center</p></div><div class="acts"><button class="btn" data-a="cust">Customize dashboard</button>${me.role==='owner'?'<button class="btn" data-a="rdl">Reset layout</button>':''}</div></div>`,
qc=w.qa?`<div class="cards qa2">${qa.map(q=>`<button class="pcard qb" data-a="qa" data-k="${q[3]}"><i class="ic">${q[0]}</i>${q[1]}</button>`).join('')}</div>`:'',
ovp=panel('Project overview',`<div class="ov"><div><small class="m">Overall progress</small><div class="big">${ov}%</div><div class="bar"><i style="width:${ov}%"></i></div></div><div><small class="m">Briz AI version</small><b>v0.4.0</b><small class="m">Development stage</small><b>Alpha</b></div><div><small class="m">Current milestone</small><b>Android app beta</b><small class="m">Next milestone</small><b>WhatsApp pilot</b></div><div><small class="m">Last update</small><b>${fd(Math.max(...S.prog.map(x=>x.u)))}</b><small class="m">Status</small><b>In development</b></div></div><div class="cards mini">${mini('Active staff',ac)}${mini('Open tasks',ot.length)}${mini('Open bugs',bugs)}${mini('Pending reviews',pr)}</div>`,bdg('DEMO DATA')),
prog=w.prog?panel('Briz AI project progress',`<div class="cards">${S.prog.map((x,i)=>`<button class="pcard" data-a="pa" data-n="${i}"><div class="row"><b>${esc(x.n)}</b><span class="m">${x.p}%</span></div><div class="bar"><i style="width:${x.p}%"></i></div><small class="m">${pst(x.p)} · updated ${fd(x.u)}</small></button>`).join('')}</div>`,can('progress')?'<button class="btn sm" data-a="prog">Update progress</button>':''):'',
mw=w.my?panel('My work',`<div class="cards"><button class="pcard" data-a="go" data-r="tasks"><small class="m">Open tasks</small><b class="n">${my.length}</b><small class="m">${soon} due within 3 days</small></button>${can('reviews')?`<button class="pcard" data-a="go" data-r="reviews"><small class="m">Pending reviews</small><b class="n">${pr}</b></button>`:''}${can('design')?`<button class="pcard" data-a="go" data-r="design"><small class="m">Design requests</small><b class="n">${dq}</b></button>`:''}<button class="pcard" data-a="go" data-r="notifs"><small class="m">Unread notifications</small><b class="n">${un}</b></button></div>${my.slice(0,4).map(t=>`<div class="ev sp" data-a="tv" data-id="${t.id}" style="cursor:pointer"><div><b>${esc(t.title)}</b><br><small class="m">${t.st} · due ${fd(t.due)}</small></div>${bdg(t.pri,pc(t.pri))}</div>`).join('')}`):'',
act=!w.act?'':can('activity')?panel('Recent activity',evs(S.act.slice(0,6)),'<button class="btn sm" data-a="go" data-r="activity">View all</button>'):panel('Design activity',S.designs.map(d=>`<div class="ev sp"><div><b>${esc(d.name)}</b><br><small class="m">v${d.v} · due ${fd(d.due)}</small></div>${bdg(d.st)}</div>`).join('')||'<p class="empty">No designs yet.</p>'),
an=!w.ann?'':panel('Announcements',S.ann.filter(a=>!a.exp||a.exp>now()).slice(0,3).map(a=>`<div class="ev sp"><div><b>${esc(a.title)}</b><br><small class="m">${esc(a.body.slice(0,90))}</small></div>${bdg(a.pri,a.pri==='High'?'e':'')}</div>`).join('')||'<p class="empty">No announcements yet.</p>','<button class="btn sm" data-a="go" data-r="ann">Open</button>');
return hero+qc+ovp+(p.first==='my'?mw+prog:prog+mw)+`<div class="g2">${act}${an}</div>`}
A.pa=d=>{const x=S.prog[+d.n],ws=x.n.split(/[ \/]/).filter(w=>w.length>2).map(w=>w.toLowerCase()),rel=S.tasks.filter(t=>vis(t)&&ws.some(w=>(t.title+t.desc+t.kind).toLowerCase().includes(w)));modal(x.n,`<div class="big">${x.p}%</div><div class="bar"><i style="width:${x.p}%"></i></div><div class="kv"><span>Status</span><b>${pst(x.p)}</b><span>Last updated</span><b>${fd(x.u)}</b><span>Responsible</span><b>${esc(nm(RESP[x.n]))}</b></div><h3>Related tasks</h3>${rel.map(t=>`<div class="ev sp"><span>${esc(t.title)}</span>${bdg(t.st)}</div>`).join('')||'<p class="m">No related tasks.</p>'}<h3>Related bugs</h3>${rel.filter(t=>t.kind.includes('Bug')).map(t=>`<div class="ev sp"><span>${esc(t.title)}</span>${bdg(t.pri,pc(t.pri))}</div>`).join('')||'<p class="m">No related bugs.</p>'}<h3>Recent activity</h3>${evs(S.act.filter(a=>a.it.includes(x.n)).slice(0,4))}`,null,'',1)};
A.cust=()=>{const p=pf(),T=(k,l)=>`<label class="ck"><input type="checkbox" name="${k}"${p.w[k]?' checked':''}> ${l}</label>`;modal('Customize dashboard',`${T('prog','Project progress')}${T('my','My work')}${T('act','Recent activity')}${T('ann','Announcements')}${T('qa','Quick actions')}<label>Show first</label><select name="first">${opts([['prog','Project progress'],['my','My work']],p.first)}</select><label>Density</label><select name="dens">${opts([['comfortable','Comfortable'],['compact','Compact'],['spacious','Spacious']],p.dens)}</select><label>Animations</label><select name="anim">${opts([['full','Full'],['reduced','Reduced'],['off','Off']],p.anim)}</select>`,f=>{['prog','my','act','ann','qa'].forEach(k=>p.w[k]=f[k]?1:0);Object.assign(p,{first:f.first,dens:f.dens,anim:f.anim});applyTheme();mx();fin('Dashboard updated')},'Save',1)};
A.rdp=()=>ask('Reset your dashboard preferences to defaults?',()=>{Object.assign(pf(),{w:{prog:1,my:1,act:1,ann:1,qa:1},first:'prog',land:'cc'});fin('Dashboard preferences reset')});A.rdl=()=>guard('staff')&&A.rdp();
A.qa=d=>{const[k,r]=d.k.split(':');k==='go'?go(r):A[k]()};
A.prog=()=>{if(!guard('progress'))return;modal('Update Briz AI progress',`<div class="g3">${S.prog.map((p,i)=>`<div><label>${esc(p.n)} (%)</label><input type="number" min="0" max="100" name="p${i}" value="${p.p}"></div>`).join('')}</div>`,f=>{if(!guard('progress'))return;let c=0;S.prog.forEach((p,i)=>{const v=Math.max(0,Math.min(100,Math.round(+f['p'+i])));if(!isNaN(v)&&v!==p.p){p.p=v;p.u=now();c++;log('Progress updated',`${p.n} → ${v}%`)}});if(c)notify('all','Progress','Briz AI project progress was updated','cc');mx();save();render();toast(c?'Progress updated':'No changes to save')})};
/* ---------- TASKS ---------- */
function tasks(){const p=pf(),q=V.q.toLowerCase(),PR={High:0,Medium:1,Low:2};let l=S.tasks.filter(t=>vis(t)&&(!q||(t.title+t.desc+nm(t.to)).toLowerCase().includes(q))&&(!V.f||t.st===V.f)&&(!V.pf||t.pri===V.pf));
l.sort(V.so==='pri'?(a,b)=>PR[a.pri]-PR[b.pri]:V.so==='new'?(a,b)=>b.at-a.at:(a,b)=>a.due-b.due);
const body=p.tv==='board'?`<div class="kb">${ST.map(s=>`<div class="col" data-drop="${s}"><h3>${s} <small class="m">${l.filter(t=>t.st===s).length}</small></h3>${l.filter(t=>t.st===s).map(t=>`<div class="kc" draggable="true" data-drag="${t.id}" data-a="tv" data-id="${t.id}"><b>${esc(t.title)}</b><p class="m">${esc(nm(t.to))} · ${fd(t.due)}</p>${bdg(t.pri,pc(t.pri))}<select data-c="ts" data-id="${t.id}" aria-label="Status">${opts(ST,t.st)}</select></div>`).join('')}</div>`).join('')}</div>`:tbl(['Task','Assignee','Priority','Status','Deadline',''],l.map(t=>`<tr class="hv"><td><button class="lk" data-a="tv" data-id="${t.id}">${esc(t.title)}</button><br><small class="m">${t.kind}</small></td><td><span class="av sm">${ini(nm(t.to))}</span>${esc(nm(t.to))}</td><td>${bdg(t.pri,pc(t.pri))}</td><td><select data-c="ts" data-id="${t.id}" aria-label="Status">${opts(ST,t.st)}</select></td><td>${dl(t)}</td><td><button class="btn sm dng" data-a="td" data-id="${t.id}">Delete</button></td></tr>`),'No tasks found.');
return panel('Tasks',srch('Search tasks',`<select data-i="f" aria-label="Status filter">${opts([['','All statuses'],...ST],V.f)}</select><select data-i="pf" aria-label="Priority filter">${opts([['','All priorities'],'High','Medium','Low'],V.pf)}</select><select data-i="so" aria-label="Sort">${opts([['','Sort: deadline'],['pri','Sort: priority'],['new','Sort: newest']],V.so)}</select><div class="seg"><button class="btn sm${p.tv!=='board'?' on':''}" data-a="tvw" data-v="list">List</button><button class="btn sm${p.tv==='board'?' on':''}" data-a="tvw" data-v="board">Board</button></div>`)+body,'<button class="btn pri" data-a="tnew">New task</button>')}
function taskM(t){const n=!t;t=t||{title:'',desc:'',to:me.id,pri:'Medium',st:'Not Started',due:now()+7*DAY,kind:'Task'};
const ex=n?'':`<div class="acts" style="margin-top:14px"><button type="button" class="btn sm" data-a="tdup" data-id="${t.id}">Duplicate</button><button type="button" class="btn sm" data-a="tarc" data-id="${t.id}">Archive</button></div><h3>Comments</h3>${t.cm.map(c=>`<p class="cm"><b>${esc(nm(c.u))}</b> · ${ft(c.at)}<br>${esc(c.x)}</p>`).join('')||'<p class="m">No comments yet.</p>'}<div class="row"><input id="cin" data-id="${t.id}" placeholder="Add a comment" aria-label="Add a comment"><button type="button" class="btn" data-a="cmt" data-id="${t.id}">Post</button></div><h3>History</h3>${t.h.slice().reverse().map(h=>`<p class="m">${ft(h[0])} · ${esc(h[1])}</p>`).join('')}`;
modal(n?'New task':'Task',`<label>Title</label><input name="title" required value="${esc(t.title)}"><label>Description</label><textarea name="desc" rows="3">${esc(t.desc)}</textarea><div class="g3"><div><label>Assignee</label><select name="to">${so(t.to)}</select></div><div><label>Priority</label><select name="pri">${opts(['Low','Medium','High'],t.pri)}</select></div><div><label>Status</label><select name="st">${opts(ST,t.st)}</select></div><div><label>Deadline</label><input type="date" name="due" value="${new Date(t.due).toISOString().slice(0,10)}"></div><div><label>Type</label><select name="kind">${opts(KD,t.kind)}</select></div></div>${ex}`,f=>{if(!guard('tasks'))return;
const x={title:f.title.trim(),desc:f.desc.trim(),to:f.to,pri:f.pri,st:f.st,kind:f.kind,due:new Date(f.due+'T12:00').getTime()||t.due};
if(n){Object.assign(t,x,{id:rid('t'),at:now(),cm:[],h:[[now(),'Created by '+me.name]]});S.tasks.unshift(t);log('Task created',x.title);x.to&&notify([x.to],'Task assignment',`New task assigned: ${x.title}`,'tasks')}
else{if(x.to!==t.to){t.h.push([now(),'Assigned to '+nm(x.to)]);log('Task assigned',x.title);x.to&&notify([x.to],'Task assignment',`New task assigned: ${x.title}`,'tasks')}if(x.pri!==t.pri)t.h.push([now(),'Priority → '+x.pri]);if(x.st!==t.st){t.h.push([now(),'Status → '+x.st]);x.st==='Completed'&&log('Task completed',x.title)}Object.assign(t,x);log('Task updated',x.title)}
mx();save();render();toast(n?'Task created successfully':'Task updated')},n?'Create task':'Save changes',1)}
A.tdup=d=>{const t=S.tasks.find(x=>x.id===d.id);if(!t||!vis(t)||!guard('tasks'))return;S.tasks.unshift({...t,id:rid('t'),title:t.title+' (copy)',st:'Not Started',at:now(),cm:[],h:[[now(),'Duplicated by '+me.name]]});log('Task duplicated',t.title);mx();fin('Task duplicated')};
A.tarc=d=>{const t=S.tasks.find(x=>x.id===d.id);if(!t||!vis(t)||!guard('tasks'))return;t.arch=1;log('Task archived',t.title);mx();fin('Task archived')};
function setSt(id,st){const t=S.tasks.find(x=>x.id===id);if(!t||!vis(t)||!guard('tasks')||t.st===st)return;t.st=st;t.h.push([now(),`Status → ${st} by ${me.name}`]);log(st==='Completed'?'Task completed':'Task status changed',t.title);t.to&&t.to!==me.id&&notify([t.to],'Task update',`"${t.title}" moved to ${st}`,'tasks');fin(`Task moved to ${st}`)}
C.ts=t=>setSt(t.dataset.id,t.value);A.tnew=()=>guard('tasks')&&taskM();A.tv=d=>{const t=S.tasks.find(x=>x.id===d.id);t&&vis(t)&&taskM(t)};A.tvw=d=>{pf().tv=d.v;save();render()};
A.td=d=>{const t=S.tasks.find(x=>x.id===d.id);if(!t||!vis(t)||!guard('tasks'))return;ask(`Delete “${esc(t.title)}”? This cannot be undone.`,()=>{S.tasks=S.tasks.filter(x=>x!==t);log('Task deleted',t.title);fin('Task deleted')})};
A.cmt=d=>{const t=S.tasks.find(x=>x.id===d.id),i=$('#cin'),x=i&&i.value.trim();if(!t||!x||!vis(t)||!guard('tasks'))return;t.cm.push({u:me.id,at:now(),x});t.h.push([now(),me.name+' commented']);log('Task comment added',t.title);t.to&&t.to!==me.id&&notify([t.to],'Task update',`New comment on "${t.title}"`,'tasks');save();taskM(t);render()};
/* ---------- REVIEWS ---------- */
function reviews(){const q=V.q.toLowerCase(),l=S.reviews.filter(r=>(!q||(r.text+r.src+r.cat+nm(r.to)).toLowerCase().includes(q))&&(!V.f||r.st===V.f));l.sort(V.so==='rating'?(a,b)=>a.rating-b.rating:(a,b)=>b.at-a.at);
return revStats()+panel('Review Center',srch('Search reviews',`<select data-i="f" aria-label="Status filter">${opts([['','All statuses'],'New','In Progress','Resolved'],V.f)}</select><select data-i="so" aria-label="Sort">${opts([['','Sort: newest'],['rating','Sort: lowest rating']],V.so)}</select>`)+tbl(['Rating','Review','Source','Date','Category','Status','Assigned','Response'],l.map(r=>`<tr class="hv" data-a="rv" data-id="${r.id}"><td class="star">${'★'.repeat(r.rating)}</td><td>${esc(r.text)}</td><td>${r.src}</td><td>${fd(r.at)}</td><td>${r.cat}</td><td>${bdg(r.st,r.st==='New'?'w':r.st==='Resolved'?'ok':'')}</td><td>${esc(nm(r.to))}</td><td>${r.resp}</td></tr>`),'No reviews found.'))}
function revM(id){const r=S.reviews.find(x=>x.id===id);if(!r||!guard('reviews'))return;modal('Review details',`<p class="star">${'★'.repeat(r.rating)}</p><p>${esc(r.text)}</p><p class="m">${r.src} · ${fd(r.at)} · ${r.cat}</p><div class="g3"><div><label>Assigned staff</label><select name="to">${so(r.to)}</select></div><div><label>Status</label><select name="st">${opts(['New','In Progress','Resolved'],r.st)}</select></div><div><label>Response</label><select name="resp">${opts(['Not Responded','Responded'],r.resp)}</select></div></div><h3>Internal notes</h3>${r.notes.map(n=>`<p class="cm"><b>${esc(nm(n.u))}</b> · ${ft(n.at)}<br>${esc(n.x)}</p>`).join('')}<label>Add note</label><textarea name="note" rows="2"></textarea>`,f=>{if(!guard('reviews'))return;if(f.to&&f.to!==r.to)notify([f.to],'New review',`Review assigned to you: "${r.text.slice(0,40)}"`,'reviews');Object.assign(r,{to:f.to,st:f.st,resp:f.resp});f.note.trim()&&r.notes.push({u:me.id,at:now(),x:f.note.trim()});log('Review updated',r.cat+' review');mx();save();render();toast('Review updated')},'Save changes',1)}
A.rv=d=>revM(d.id);
/* ---------- DESIGN STUDIO ---------- */
function design(){return panel('Design Studio',tbl(['Design','Designer','Reviewer','Deadline','Version','Status',''],S.designs.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(nm(d.by))}</td><td>${esc(nm(d.rev))}</td><td>${fd(d.due)}</td><td>v${d.v}</td><td>${bdg(d.st,d.st==='Approved'?'ok':d.st==='In Revision'?'w':'')}</td><td class="acts">${['Draft','In Revision'].includes(d.st)?`<button class="btn sm pri" data-a="ds" data-k="sub" data-id="${d.id}">Submit</button>`:''}${can('dreview')&&['Submitted','Awaiting Approval'].includes(d.st)?`<button class="btn sm" data-a="ds" data-k="rev" data-id="${d.id}">Request revision</button><button class="btn sm pri" data-a="ds" data-k="ok" data-id="${d.id}">Approve</button>`:''}<button class="btn sm" data-a="dfb" data-id="${d.id}">Feedback (${d.fb.length})</button></td></tr>`),'No designs yet.'),'<button class="btn pri" data-a="dnew">New design</button>')}
A.ds=d=>{const x=S.designs.find(z=>z.id===d.id);if(!x||!guard(d.k==='sub'?'design':'dreview'))return;
if(d.k==='sub'){x.st=x.st==='Draft'?'Submitted':'Awaiting Approval';log('Design submitted',x.name);notify([x.rev],'Design feedback',`"${x.name}" was submitted for review`,'design');fin('Design submitted')}
else if(d.k==='ok'){x.st='Approved';log('Design approved',x.name);notify([x.by],'Design feedback',`"${x.name}" was approved`,'design');fin('Design approved')}
else{x.st='In Revision';x.v++;log('Revision requested',x.name);notify([x.by],'Design feedback',`Revision requested for "${x.name}"`,'design');fin('Revision requested')}};
A.dfb=d=>{const x=S.designs.find(z=>z.id===d.id);if(!x||!guard('design'))return;modal(x.name,`${x.fb.map(n=>`<p class="cm"><b>${esc(nm(n.u))}</b> · ${ft(n.at)}<br>${esc(n.x)}</p>`).join('')||'<p class="m">No feedback yet.</p>'}<label>Add feedback</label><textarea name="x" rows="3" required></textarea>`,f=>{if(!guard('design'))return;x.fb.push({u:me.id,at:now(),x:f.x.trim()});log('Design feedback added',x.name);notify([me.id===x.by?x.rev:x.by],'Design feedback',`New feedback on "${x.name}"`,'design');mx();fin('Feedback added')},'Add feedback')};
A.dnew=()=>guard('design')&&modal('New design',`<label>Name</label><input name="name" required><label>Reviewer</label><select name="rev">${opts(S.staff.filter(s=>s.role==='owner').map(s=>[s.id,s.name]))}</select><label>Deadline</label><input type="date" name="due" required>`,f=>{if(!guard('design'))return;S.designs.unshift({id:rid('d'),name:f.name.trim(),by:me.id,rev:f.rev,due:new Date(f.due+'T12:00').getTime(),st:'Draft',v:1,fb:[]});log('Design created',f.name.trim());mx();fin('Design created')},'Create design');
/* ---------- ANALYTICS / ACTIVITY ---------- */
const RG=[['7','7 days'],['30','30 days'],['90','90 days'],['180','6 months'],['all','All time']],AF={All:0,Security:a=>a.sec,Tasks:a=>/task/i.test(a.a),Reviews:a=>/review/i.test(a.a),Designs:a=>/design|revision/i.test(a.a),Staff:a=>/staff|invit|account|session/i.test(a.a),Announcements:a=>/announcement/i.test(a.a)};
function analytics(){const full=me.role!=='ui',R=V.rng||'30',lim=R==='all'?0:now()-R*DAY,rs=S.reviews.filter(r=>r.at>=lim),ts=S.tasks.filter(t=>vis(t)&&t.at>=lim),open=ts.filter(t=>t.st!=='Completed'),n=rs.length,avg=n?(rs.reduce((a,r)=>a+r.rating,0)/n).toFixed(1):'–',rr=n?Math.round(rs.filter(r=>r.resp==='Responded').length/n*100):0,tc=ts.length?Math.round((ts.length-open.length)/ts.length*100):0,ov=Math.round(S.prog.reduce((a,x)=>a+x.p,0)/S.prog.length),d0=new Date(),
mo=[...Array(6)].map((_,i)=>{const d=new Date(d0.getFullYear(),d0.getMonth()-5+i,1);return[d.toLocaleString(undefined,{month:'short'}),S.reviews.filter(r=>{const x=new Date(r.at);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()}).length]}),m6=Math.max(1,...mo.map(m=>m[1])),
st=[...(full?[['Reviews',n],['Average rating',avg],['Pending responses',rs.filter(r=>r.resp!=='Responded').length]]:[]),['Open bugs',open.filter(t=>t.kind.includes('Bug')).length],['Completed tasks',ts.length-open.length],['Active staff',S.staff.filter(s=>s.status==='active').length]];
return`<div class="chips">${RG.map(r=>`<button class="btn sm${R===r[0]?' on':''}" data-a="rng" data-v="${r[0]}">${r[1]}</button>`).join('')}</div><section class="panel strip" style="--n:${st.length}">${st.map(s=>`<div><small>${s[0]}</small><b>${s[1]}</b></div>`).join('')}</section><section class="panel"><div class="dns">${full?donut(rr,'Review response rate'):''}${donut(tc,'Tasks completed')}${donut(ov,'Project progress')}</div></section><div class="g2">${full?panel('Review trends (6 months)',mo.map(m=>bar(m[0],m[1],m6)).join('')):''}${panel('Task distribution',ST.map(s=>bar(s,ts.filter(t=>t.st===s).length,ts.length)).join(''))}</div><div class="g2">${panel('Project progress',S.prog.map(x=>bar(x.n,x.p,100)).join(''))}${panel('Staff workload (open tasks)',S.staff.map(s=>bar(s.name,open.filter(t=>t.to===s.id).length,open.length)).join(''))}</div>`}
A.rng=d=>{V.rng=d.v;render()};
function activity(){const q=V.q.toLowerCase(),f=AF[V.af||'All'],l=S.act.filter(a=>(!q||(a.a+a.it+nm(a.u)).toLowerCase().includes(q))&&(!f||f(a)));return panel('Activity',`<div class="chips">${Object.keys(AF).map(k=>`<button class="btn sm${(V.af||'All')===k?' on':''}" data-a="af" data-v="${k}">${k}</button>`).join('')}</div>`+srch('Search activity')+evs(l.slice(0,60)))}
A.af=d=>{V.af=d.v;render()};
/* ---------- ANNOUNCEMENTS / NOTIFICATIONS ---------- */
function ann(){const l=S.ann.filter(a=>!a.exp||a.exp>now()||can('annw')).sort((a,b)=>b.pin-a.pin||b.at-a.at);return panel('Announcements',l.length?l.map(a=>`<div class="ar${a.rd.includes(me.id)?'':' un'}"><div><b>${esc(a.title)}</b> ${a.pin?bdg('Pinned','ok'):''}${bdg(a.pri,a.pri==='High'?'e':'')}${a.exp&&a.exp<now()?bdg('Expired'):''}<p>${esc(a.body)}</p><small class="m">${esc(nm(a.by))} · ${fd(a.at)}${a.exp?' · expires '+fd(a.exp):''}</small></div><div class="acts">${a.rd.includes(me.id)?'':`<button class="btn sm" data-a="ard" data-id="${a.id}">Mark as read</button>`}${can('annw')?`<button class="btn sm" data-a="apin" data-id="${a.id}">${a.pin?'Unpin':'Pin'}</button><button class="btn sm" data-a="aed" data-id="${a.id}">Edit</button><button class="btn sm dng" data-a="adl" data-id="${a.id}">Delete</button>`:''}</div></div>`).join(''):'<p class="empty">No announcements yet.</p>',can('annw')?'<button class="btn pri" data-a="anew">New announcement</button>':'')}
function annM(a){const n=!a;a=a||{title:'',body:'',pri:'Normal',exp:0};modal(n?'New announcement':'Edit announcement',`<label>Title</label><input name="title" required value="${esc(a.title)}"><label>Message</label><textarea name="body" rows="4" required>${esc(a.body)}</textarea><div class="g3"><div><label>Priority</label><select name="pri">${opts(['Normal','High'],a.pri)}</select></div><div><label>Expiry date (optional)</label><input type="date" name="exp" value="${a.exp?new Date(a.exp).toISOString().slice(0,10):''}"></div></div>`,f=>{if(!guard('annw'))return;const d={title:f.title.trim(),body:f.body.trim(),pri:f.pri,exp:f.exp?new Date(f.exp+'T23:59').getTime():0};
if(n){S.ann.unshift({id:rid('a'),...d,pin:0,at:now(),by:me.id,rd:[me.id]});notify('all','Announcement',`New announcement: ${d.title}`,'ann')}else Object.assign(a,d,{rd:[me.id]});log(n?'Announcement created':'Announcement edited',d.title);mx();save();render();toast(n?'Announcement published':'Announcement updated')},n?'Publish':'Save changes')}
const ga=id=>S.ann.find(x=>x.id===id),gn=id=>S.notifs.find(x=>x.id===id);
A.anew=()=>guard('annw')&&annM();A.aed=d=>guard('annw')&&annM(ga(d.id));A.ard=d=>{ga(d.id).rd.push(me.id);fin('Marked as read')};
A.apin=d=>{if(!guard('annw'))return;const a=ga(d.id);a.pin=+!a.pin;log(a.pin?'Announcement pinned':'Announcement unpinned',a.title);fin(a.pin?'Announcement pinned':'Announcement unpinned')};
A.adl=d=>{if(!guard('annw'))return;const a=ga(d.id);ask(`Delete announcement “${esc(a.title)}”?`,()=>{S.ann=S.ann.filter(x=>x!==a);log('Announcement deleted',a.title);fin('Announcement deleted')})};
const NF=['All','Unread','Security','Tasks','Reviews','Designs','Announcements','Account'];
function notifs(){const f=V.nf||'All',l=mine().filter(n=>f==='All'||(f==='Unread'?!n.rd.includes(me.id):NCAT[n.type]===f));return panel('Notifications',`<div class="chips">${NF.map(k=>`<button class="btn sm${f===k?' on':''}" data-a="nf" data-v="${k}">${k}</button>`).join('')}</div>`+(l.length?l.map(n=>`<div class="ar${n.rd.includes(me.id)?'':' un'}"><div>${bdg(n.type)} <span>${esc(n.text)}</span><br><small class="m">${ft(n.at)}</small></div><div class="acts"><button class="btn sm" data-a="nop" data-id="${n.id}">Open</button>${n.rd.includes(me.id)?'':`<button class="btn sm" data-a="nrd" data-id="${n.id}">Mark as read</button>`}<button class="btn sm" data-a="ncl" data-id="${n.id}">Clear</button></div></div>`).join(''):'<p class="empty">You are all caught up.</p>'),'<div class="acts"><button class="btn" data-a="nall">Mark all as read</button><button class="btn dng" data-a="nclr">Clear all</button></div>')}
A.nf=d=>{V.nf=d.v;render()};A.nclr=()=>ask('Clear all notifications?',()=>{mine().forEach(n=>n.cl.push(me.id));fin('Notifications cleared')});
A.nop=d=>{const n=gn(d.id);n.rd.includes(me.id)||n.rd.push(me.id);save();go(n.r&&can(perm(n.r))?n.r:'notifs')};A.nrd=d=>{gn(d.id).rd.push(me.id);fin('Marked as read')};A.ncl=d=>{gn(d.id).cl.push(me.id);fin('Notification cleared')};A.nall=()=>{mine().forEach(n=>n.rd.includes(me.id)||n.rd.push(me.id));fin('All notifications marked as read')};
/* ---------- SECURITY / SETTINGS / PROFILE ---------- */
const sessT=()=>tbl(['Device','Started','Status',''],S.sess.filter(s=>s.uid===me.id).map(s=>`<tr><td>${esc(s.dev)}</td><td>${ft(s.at)}</td><td>${s.id===gs()?bdg('This device','ok'):bdg('Other')}</td><td><button class="btn sm dng" data-a="srv" data-id="${s.id}">${s.id===gs()?'Log out':'Revoke'}</button></td></tr>`),'No active sessions.');
function security(){const ev=S.act.filter(a=>a.sec&&(a.u===me.id||me.role==='owner')).slice(0,10),fl=S.act.filter(a=>a.a==='Failed login attempt'&&a.u===me.id).length;
return panel('Account security',`<div class="strip" style="--n:4"><div><small>Account status</small><b>Active</b></div><div><small>Last login</small><b>${ft(me.last)}</b></div><div><small>Failed attempts</small><b>${fl}</b></div><div><small>Authentication</small><b>DEMO MODE</b></div></div><p class="m">Temporary security code at sign-in: ${bdg('FUTURE SECURITY LAYER','w')} not active yet.</p>`)+panel('Active sessions',sessT(),'<button class="btn" data-a="sro">Log out other devices</button>')+panel('Security timeline',evs(ev))}
A.srv=d=>{const s=S.sess.find(x=>x.id===d.id);if(!s||s.uid!==me.id)return;S.sess=S.sess.filter(x=>x!==s);log('Session revoked',s.dev,me.id,1);if(s.id===gs())return logout();fin('Session revoked')};
A.sro=()=>{S.sess=S.sess.filter(s=>s.uid!==me.id||s.id===gs());log('Other sessions revoked','All other devices',me.id,1);fin('Other devices logged out')};
const SCAT=['Account','Appearance','Dashboard','Notifications','Security','Sessions','Accessibility','Privacy & Data','System','About'],NL=['Task assignments','Task updates','Task deadlines','Reviews','Design feedback','Announcements','Security alerts','Account events'];
function setP(k,v){const p=pf(),a=k.split('.');a.length>1?p[a[0]][a[1]]=v:p[k]=v;applyTheme();save();render();try{const q=document.querySelector(`[data-k="${k}"][data-v="${v}"]`)||document.querySelector(`[data-k="${k}"]`);q&&q.focus()}catch(e){}}
A.sv=d=>setP(d.k,d.v);C.pv=t=>setP(t.dataset.k,t.value);
A.tgl=d=>{const p=pf();if(d.k==='rm')return setP('anim',p.anim==='full'?'reduced':'full');const a=d.k.split('.');let c=a.length>1?p[a[0]][a[1]]:p[d.k];if(c===undefined)c=1;setP(d.k,c?0:1)};
A.sro=()=>ask('Log out all other devices? They will need to sign in again.',()=>{S.sess=S.sess.filter(s=>s.uid!==me.id||s.id===gs());log('Other sessions revoked','All other devices',me.id,1);fin('Other devices logged out')});
A.exp=()=>{const{auth,sess,fails,...d}=S;modal('Export demo data',`<p class="m">Copy this JSON as a backup. Passwords and sessions are not included.</p><textarea rows="12" readonly onfocus="this.select()">${esc(JSON.stringify(d,null,1))}</textarea>`,null,'',1)};
function settings(){const p=pf(),row=(t,d,c)=>`<div class="set"><div><b>${t}</b><p>${d}</p></div>${c}</div>`,
sg=(k,o)=>`<div class="sg" role="group">${o.map(x=>`<button class="${p[k]===x[0]?'on':''}" data-a="sv" data-k="${k}" data-v="${x[0]}" aria-pressed="${p[k]===x[0]}">${x[1]}</button>`).join('')}</div>`,
tg=(k,l)=>{const v=k.split('.').reduce((a,x)=>a[x],p),on=k.startsWith('np.')?v!==0:!!v;return`<button class="tg${on?' on':''}" role="switch" aria-checked="${on}" aria-label="${l}" data-a="tgl" data-k="${k}"></button>`},
sess=S.sess.filter(s=>s.uid===me.id),lp=S.act.find(a=>a.u===me.id&&/Password (changed|reset)|Account activated/.test(a.a)),fl=S.act.filter(a=>a.a==='Failed login attempt'&&a.u===me.id).length,ls=(()=>{try{return localStorage.getItem(KEY)||''}catch(e){return''}})(),
dn=[['comfortable','Comfortable'],['compact','Compact'],['spacious','Spacious']],
B={Account:`<div class="kv"><span>Name</span><b>${esc(me.name)}</b><span>Staff ID</span><b>${me.id}</b><span>Gmail</span><b>${esc(me.email)}</b><span>Role</span><b>${RN[me.role]}</b><span>Account status</span><b>Active</b><span>Joined</span><b>${fd(me.joined)}</b><span>Last login</span><b>${ft(me.last)}</b></div><p class="m">Account details are managed by the TRUEAI Owner.</p>`,
Appearance:row('Theme','Changes apply instantly.',sg('theme',[['dark','Dark'],['light','Light'],['system','System']]))+row('Accent','Highlight color across Headquarters.',sg('accent',[['blue','Blue'],['slate','Blue-gray']]))+row('Density','Spacing across every page.',sg('dens',dn))+row('Animations','Full, reduced or none.',sg('anim',[['full','Full'],['reduced','Reduced'],['off','Off']]))+row('Glass effects','Blur behind panels and dialogs.',tg('glass','Glass effects'))+row('Background effects','Soft ambient light.',tg('bgfx','Background effects')),
Dashboard:row('Default landing page','Where you land after signing in.',`<select data-c="pv" data-k="land" aria-label="Default landing page">${opts(NAV.filter(n=>can(perm(n[0]))).map(n=>[n[0],n[1]]),p.land)}</select>`)+[['prog','Project progress'],['act','Recent activity'],['my','My work'],['ann','Announcements'],['qa','Quick actions']].map(x=>row('Show '+x[1].toLowerCase(),'Display on the Command Center.',tg('w.'+x[0],x[1]))).join('')+row('Dashboard density','Spacing across Headquarters.',sg('dens',dn))+row('Reset dashboard layout','Restore default widgets and order.',`<button class="btn" data-a="${me.role==='owner'?'rdl':'rdp'}">Reset</button>`),
Notifications:row('Notification level','Choose what reaches you.',sg('lvl',[['all','All'],['imp','Important only'],['none','None']]))+NL.map(l=>row(l,'Show in your notification center.',tg('np.'+l,l))).join('')+row('Notification sound','Off by default.',tg('snd','Notification sound'))+row('Mark all notifications as read','Clears every unread indicator.','<button class="btn" data-a="nall">Mark all as read</button>'),
Security:`<div class="kv"><span>Authentication mode</span><b>DEMO MODE</b><span>Password status</span><b>Set (salted hash)</b><span>Last password change</span><b>${lp?ft(lp.at):'Never'}</b><span>Failed login attempts</span><b>${fl}</b><span>Active sessions</span><b>${sess.length}</b></div><p class="warn">DEMO MODE. Server-side authentication is required for production.</p><div class="acts"><button class="btn pri" data-a="cpw">Change password</button><button class="btn" data-a="sro">Log out other devices</button><button class="btn" data-a="go" data-r="security">View security events</button></div><p class="m">Temporary security code: ${bdg('FUTURE SECURITY LAYER','w')}</p>`,
Sessions:`<div class="acts" style="margin-bottom:14px"><button class="btn dng" data-a="sro">Log out all other devices</button></div>`+tbl(['Browser','Platform','Signed in','Status',''],sess.map(s=>{const[a,b]=s.dev.split(' · ');return`<tr><td>${esc(b||'Browser')}</td><td>${esc(a)}</td><td>${ft(s.at)}</td><td>${s.id===gs()?bdg('This device','ok'):bdg('Other')}</td><td><button class="btn sm dng" data-a="srv" data-id="${s.id}">${s.id===gs()?'Log out':'Revoke'}</button></td></tr>`}),'No active sessions.'),
Accessibility:row('Reduced motion','Minimizes animation.',`<button class="tg${p.anim!=='full'?' on':''}" role="switch" aria-checked="${p.anim!=='full'}" aria-label="Reduced motion" data-a="tgl" data-k="rm"></button>`)+row('Larger text','Increases text size.',tg('big','Larger text'))+row('Higher contrast','Stronger borders and text.',tg('hc','Higher contrast'))+row('Control size','Compact or comfortable controls.',sg('dens',dn.slice(0,2)))+row('Focus indicators','Always visible for keyboard navigation.','<span class="bd ok">Always on</span>'),
'Privacy & Data':`<div class="kv"><span>Local storage usage</span><b>${(ls.length/1024).toFixed(1)} KB</b><span>Demo data</span><b>Seeded demo data</b><span>Account data</span><b>${esc(me.email)}</b><span>Session data</span><b>${sess.length} on this account</b></div><div class="acts"><button class="btn" data-a="exp">Export demo data</button><button class="btn" data-a="nclr">Clear notifications</button><button class="btn" data-a="rdp">Reset dashboard preferences</button>${can('staff')?'<button class="btn dng" data-a="rst">Reset all demo data</button>':''}</div>`,
System:`<div class="kv"><span>Version</span><b>TRUEAI Headquarters 1.1.0</b><span>Build status</span><b><i class="dot"></i>Operational</b><span>Environment</span><b>Browser prototype</b><span>Authentication mode</span><b>DEMO MODE</b><span>Storage mode</span><b>Browser localStorage</b><span>Browser</span><b>${esc((navigator.userAgent.match(/(Edg|Chrome|Firefox|Safari)/)||['Unknown'])[0])}</b><span>Screen size</span><b>${innerWidth} × ${innerHeight}</b></div>`,
About:`<h3>TRUEAI</h3><p>TRUEAI Headquarters<br><span class="m">Briz AI Operations &amp; Staff Command Center</span></p><p>TRUEAI is the company. Briz AI is TRUEAI's AI product.</p><p class="m">Building intelligence, one step ahead.</p>`};
return panel('Settings',`<div class="st"><nav class="snav" aria-label="Settings sections">${SCAT.map(t=>`<button class="nv${V.tab===t?' on':''}" data-a="tab" data-t="${t}">${t}</button>`).join('')}</nav><div class="sbody">${B[V.tab]||B.Account}</div></div>`)}
A.cpw=()=>modal('Change password',`<label>Current password</label><input type="password" name="c" required autocomplete="current-password"><label>New password</label><input type="password" name="n" data-i="pw" required autocomplete="new-password"><small id="sm" class="m"></small><label>Confirm new password</label><input type="password" name="n2" required autocomplete="new-password">`,async f=>{const a=S.auth[me.id];if(await hp(f.c,a.salt)!==a.hash)return toast('Current password is incorrect.');const e=pwErr(f.n,f.n2);if(e)return toast(e);const salt=rnd();S.auth[me.id]={salt,hash:await hp(f.n,salt)};S.sess=S.sess.filter(s=>s.uid!==me.id||s.id===gs());log('Password changed','Other sessions revoked',me.id,1);notify([me.id],'Security','Your password was changed','security');mx();fin('Password updated')},'Update password');
A.rst=()=>guard('staff')&&ask('Reset all demo data and sign out on this browser?',()=>{try{localStorage.removeItem(KEY);ss(null)}catch(e){}location.reload()});
function profile(){const R={owner:'Founder / Owner, TRUEAI & Briz AI',co:'Co-Administrator, TRUEAI',ui:'UI Designer, TRUEAI'}[me.role],my=S.tasks.filter(t=>t.to===me.id&&t.st!=='Completed'&&vis(t)).slice(0,4),inv=S.prog.filter(x=>RESP[x.n]===me.id);
return panel('Profile',`<div class="prof"><div class="av big">${ini(me.name)}</div><div class="kv"><span>Name</span><b>${esc(me.name)}</b><span>Title</span><b>${R}</b><span>Staff ID</span><b>${me.id}</b><span>Role</span><b>${RN[me.role]}</b><span>Account status</span><b>Active</b><span>Joined</span><b>${fd(me.joined)}</b><span>Last login</span><b>${ft(me.last)}</b><span>Responsibilities</span><b>${RT[me.role]}</b></div></div><p class="m">TRUEAI is the company. Briz AI is TRUEAI's AI product.</p>`)+`<div class="g2">${panel('Current tasks',my.map(t=>`<div class="ev sp" data-a="tv" data-id="${t.id}" style="cursor:pointer"><div><b>${esc(t.title)}</b><br><small class="m">${t.st} · due ${fd(t.due)}</small></div>${bdg(t.pri,pc(t.pri))}</div>`).join('')||'<p class="empty">No open tasks.</p>')}${panel('Recent activity',evs(S.act.filter(a=>a.u===me.id).slice(0,5)))}</div>`+panel('Project involvement',inv.map(x=>bar(x.n,x.p,100)).join('')||'<p class="empty">No project areas assigned.</p>',bdg('DEMO'))}
/* ---------- STAFF MANAGEMENT (OWNER) ---------- */
function staff(){return panel('Staff directory',tbl(['Staff','Staff ID','Role','Account','Invitation','Last login','Sessions',''],S.staff.map(s=>{const n=S.sess.filter(x=>x.uid===s.id).length;return`<tr class="hv" data-a="sp" data-id="${s.id}"><td><span class="av sm">${ini(s.name)}</span> ${esc(s.name)}</td><td>${s.id}</td><td>${RN[s.role]}</td><td>${bdg(s.status==='active'?'Active':s.status==='inactive'?'Inactive':'Not activated',s.status==='active'?'ok':'')}</td><td>${invS(s)}</td><td>${ft(s.last)}</td><td>${n}</td><td class="acts">${s.role==='owner'?bdg('Protected'):`<button class="btn sm" data-a="stf" data-k="tog" data-id="${s.id}">${s.status==='inactive'?'Reactivate':'Deactivate'}</button>${s.inv==='Pending'&&s.status==='invited'?`<button class="btn sm" data-a="stf" data-k="rvk" data-id="${s.id}">Revoke invitation</button>`:''}${n?`<button class="btn sm" data-a="stf" data-k="ses" data-id="${s.id}">Revoke sessions</button>`:''}`}</td></tr>`}),''),'<button class="btn pri" data-a="inv">Invite staff</button>')}
A.sp=d=>{if(!guard('staff'))return;const s=S.staff.find(x=>x.id===d.id);if(!s)return;const ts=S.tasks.filter(t=>t.to===s.id&&!t.arch),op=ts.filter(t=>t.st!=='Completed').length;modal(s.name,`<div class="prof"><div class="av big">${ini(s.name)}</div><div class="kv"><span>Staff ID</span><b>${s.id}</b><span>Role</span><b>${RN[s.role]}</b><span>Gmail</span><b>${esc(s.email)}</b><span>Account</span><b>${s.status==='active'?'Active':s.status==='inactive'?'Inactive':'Not activated'}</b><span>Invitation</span><b>${invS(s)}</b><span>Last login</span><b>${ft(s.last)}</b><span>Workload</span><b>${op} open · ${ts.length-op} done</b><span>Sessions</span><b>${S.sess.filter(x=>x.uid===s.id).length}</b></div></div><p class="m">${RT[s.role]}</p><h3>Recent activity</h3>${evs(S.act.filter(a=>a.u===s.id).slice(0,5))}`,null,'',1)};
A.stf=d=>{if(!guard('staff'))return;const s=S.staff.find(x=>x.id===d.id);if(!s||s.role==='owner')return toast('The Owner account is protected.');
if(d.k==='tog')ask(`${s.status==='inactive'?'Reactivate':'Deactivate'} ${esc(s.name)}?`,()=>{if(s.status==='inactive')s.status=S.auth[s.id]?'active':'invited';else{s.status='inactive';S.sess=S.sess.filter(x=>x.uid!==s.id)}log(s.status==='inactive'?'Account deactivated':'Account reactivated',s.name,me.id,1);fin('Account updated')});
else if(d.k==='rvk'){s.inv='Revoked';log('Invitation revoked',s.name,me.id,1);fin('Invitation revoked')}
else{S.sess=S.sess.filter(x=>x.uid!==s.id);log('Session revoked',s.name+' (all sessions)',me.id,1);fin('Sessions revoked')}};
A.inv=()=>{if(!guard('staff'))return;modal('Invite staff',`<label>Name</label><input name="name" required><label>Gmail</label><input name="email" type="email" required pattern=".+@gmail\\.com"><label>Assigned Staff ID</label><input name="id" required value="TRUEAI-HQ-${String(S.staff.length+1).padStart(4,'0')}"><div class="g3"><div><label>Role</label><select name="role">${opts([['co','Co-Administrator'],['ui','UI Designer']])}</select></div><div><label>Expires in</label><select name="days">${opts([['3','3 days'],['7','7 days'],['14','14 days']],'7')}</select></div></div>`,f=>{if(!guard('staff'))return;const id=f.id.trim().toUpperCase(),em=f.email.trim().toLowerCase(),nmv=f.name.trim();
if(!/^TRUEAI-HQ-\d{4}$/.test(id)||S.staff.some(s=>s.id===id||s.email===em))return toast('Staff ID or Gmail is invalid or already in use.');if(!['co','ui'].includes(f.role))return toast('That role cannot be assigned.');
S.staff.push({id,name:nmv,email:em,role:f.role,status:'invited',inv:'Pending',exp:now()+f.days*DAY,last:0});log('Staff invited',nmv);notify([me.id],'Invitation',`Invitation created for ${nmv}`,'staff');save();render();
modal('Invitation created',`<p class="demo">DEMO MODE — no email was sent. Simulated message:</p><div class="mail"><b>To:</b> ${esc(em)}<br><b>Subject:</b> Your TRUEAI Headquarters invitation<br><br>Hello ${esc(nmv)}, you have been invited to TRUEAI Headquarters as ${RN[f.role]}. Your Staff ID is ${id}. Use “First-time activation” on the sign-in page. This invitation expires in ${f.days} days.</div>`,null);toast('Invitation created')},'Create invitation')};
/* ---------- COMMAND PALETTE / SEARCH ---------- */
const CMD=[['Create','＋','Create Task','tasks',()=>{go('tasks');A.tnew()},'N'],['Create','✎','Create Announcement','annw',()=>{go('ann');A.anew()}],['Create','⊕','Invite Staff','staff',()=>{go('staff');A.inv()}],['Navigate','◎','Open Command Center','cc',()=>go('cc')],['Navigate','★','Open Reviews','reviews',()=>go('reviews')],['Navigate','◧','Open Design Studio','design',()=>go('design')],['Navigate','▤','Open Analytics','analytics',()=>go('analytics')],['Navigate','◔','Open Notifications','notifs',()=>go('notifs')],['Navigate','⛨','Open Security','security',()=>go('security')],['Navigate','◉','Open Staff Management','staff',()=>go('staff')],['Navigate','⚙','Open Settings','settings',()=>go('settings')],['System','◐','Toggle Theme','cc',()=>setP('theme',document.documentElement.dataset.theme==='dark'?'light':'dark')],['System','⏻','Logout','cc',()=>A.out()]];
function pItems(q){q=q.trim().toLowerCase();const m=x=>!q||x.toLowerCase().includes(q),o=[];
if(!q)pf().rs.slice(0,3).forEach(r=>o.push(['Recent','↺',r,()=>{A.pal();$('#pq').value=r;pl(r)}]));
CMD.filter(c=>can(c[3])&&m(c[2])).forEach(c=>o.push([c[0],c[1],c[2],c[4],c[5]]));
if(q){can('staff')&&S.staff.filter(s=>m(s.name+s.id)).forEach(s=>o.push(['Staff','◉',s.name,()=>A.sp({id:s.id})]));
can('tasks')&&S.tasks.filter(t=>vis(t)&&m(t.title)).forEach(t=>o.push(['Tasks','☑',t.title,()=>{go('tasks');taskM(t)}]));
can('reviews')&&S.reviews.filter(r=>m(r.text)).forEach(r=>o.push(['Reviews','★',r.text,()=>{go('reviews');revM(r.id)}]));
S.ann.filter(a=>m(a.title)).forEach(a=>o.push(['Announcements','✎',a.title,()=>go('ann')]));
can('activity')&&S.act.filter(a=>m(a.a+a.it)).slice(0,4).forEach(a=>o.push(['Activity','◷',a.a+' · '+a.it,()=>go('activity')]));
mine().filter(n=>m(n.text)).forEach(n=>o.push(['Notifications','◔',n.text,()=>go('notifs')]));
can('design')&&S.designs.filter(d=>m(d.name)).forEach(d=>o.push(['Designs','◧',d.name,()=>go('design')]))}
return o.slice(0,14)}
const drawP=()=>{let c='';$('#pr').innerHTML=PI.length?PI.map((x,i)=>{const h=x[0]!==c?`<div class="ph">${x[0]}</div>`:'';c=x[0];return h+`<button class="pi${i===PX?' on':''}" data-a="pick" data-n="${i}"><i>${x[1]}</i><span>${esc(x[2])}</span>${x[4]?`<kbd>${x[4]}</kbd>`:''}</button>`}).join(''):'<p class="empty">No results found.</p>'},pl=q=>{PI=pItems(q);PX=0;drawP()};
A.pal=()=>{const p=$('#pal');p.className='on';p.innerHTML='<div class="pb"><input id="pq" data-i="pq" placeholder="Search or type a command…" aria-label="Command palette" autocomplete="off"><div id="pr" role="listbox"></div><div class="pf"><span><kbd>↑</kbd><kbd>↓</kbd> navigate</span><span><kbd>↵</kbd> select</span><span><kbd>Esc</kbd> close</span></div></div>';pl('');$('#pq').focus()};
A.pc=()=>{const p=$('#pal');p.className='';p.innerHTML=''};A.pick=d=>{const x=PI[d.n],q=(($('#pq')||{}).value||'').trim();A.pc();if(!x)return;if(q&&x[0]!=='Recent'){const p=pf();p.rs=[q,...p.rs.filter(r=>r!==q)].slice(0,5);save()}x[3]()};
/* ---------- EVENTS ---------- */
document.addEventListener('click',e=>{if(e.target.closest('select,input,textarea'))return;const t=e.target.closest('[data-a]');if(!t)return;e.preventDefault();A[t.dataset.a]&&A[t.dataset.a](t.dataset,t,e)});
document.addEventListener('submit',e=>{const f=e.target.closest('form');if(!f||!f.dataset.f)return;e.preventDefault();const v=Object.fromEntries(new FormData(f));f.dataset.f==='modal'?MH&&MH(v):F[f.dataset.f](v,f)});
document.addEventListener('change',e=>{const c=e.target.dataset&&e.target.dataset.c;c&&C[c](e.target)});
document.addEventListener('input',e=>{const t=e.target,k=t.dataset&&t.dataset.i;if(!k)return;if(k==='pw'){$('#sm').textContent=strength(t.value);return}if(k==='pq'){pl(t.value);return}V[k]=t.value;const id=t.id,p=t.selectionStart;render();const n=id&&document.getElementById(id);if(n){n.focus();try{n.setSelectionRange(p,p)}catch(x){}}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();me&&A.pal();return}SK(e);if(e.key==='Escape'){A.pc();mx()}
if($('#pal').className==='on'){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();PX=(PX+(e.key==='ArrowDown'?1:-1)+PI.length)%(PI.length||1);drawP()}if(e.key==='Enter'&&PI[PX]){e.preventDefault();A.pick({n:PX})}}
if(e.key==='Enter'&&e.target.id==='cin'){e.preventDefault();A.cmt({id:e.target.dataset.id})}});
$('#modal').addEventListener('click',e=>e.target.id==='modal'&&mx());$('#pal').addEventListener('click',e=>e.target.id==='pal'&&A.pc());
document.addEventListener('dragstart',e=>{const c=e.target.closest&&e.target.closest('[data-drag]');c&&e.dataTransfer.setData('text/plain',c.dataset.drag)});
document.addEventListener('dragover',e=>{e.target.closest&&e.target.closest('[data-drop]')&&e.preventDefault()});
document.addEventListener('drop',e=>{const c=e.target.closest&&e.target.closest('[data-drop]');if(c){e.preventDefault();setSt(e.dataTransfer.getData('text/plain'),c.dataset.drop)}});
(function(){const s=S.sess.find(x=>x.id===gs()),u=s&&S.staff.find(x=>x.id===s.uid&&x.status==='active');if(u){me=u;V.r=location.hash.slice(2)||'cc';applyTheme();render()}else authView()})();

